#!/bin/sh
# java -D.level=INFO -Dhandlers=java.util.logging.ConsoleHandler -Djava.util.logging.ConsoleHandler.level=INFO -Djava.util.logging.ConsoleHandler.formatter=com.eas.util.logging.PlatypusFormatter -Djava.util.logging.config.class=com.eas.util.logging.LoggersConfig -cp /home/jskonst/workspace/Altsoft/PlatypusJS/application/bin/Server.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/api/*:/home/jskonst/workspace/Altsoft/PlatypusJS/application/ext/*:/home/jskonst/workspace/Altsoft/PlatypusJS/application/ext/ com.eas.server.ServerMain -datasource eas -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser eas -dbpassword eas -dbschema EAS -datasource easHR -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser hr -dbpassword hr -dbschema HR -appelement start.js -url file:///home/jskonst/workspace/Altsoft/PlatypusTests/ -iface 0.0.0.0:8500 -protocols 8500:platypus

# java -D.level=INFO -Dhandlers=java.util.logging.ConsoleHandler -Djava.util.logging.ConsoleHandler.level=INFO -Djava.util.logging.ConsoleHandler.formatter=com.eas.util.logging.PlatypusFormatter -Djava.util.logging.config.class=com.eas.util.logging.LoggersConfig -cp  /home/jskonst/workspace/Altsoft/PlatypusJS/application/api:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/thirdparty/j-interop/j-interop.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/thirdparty/j-interop/j-interopdeps.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/thirdparty/j-interop/jcifs-1.2.19.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/thirdparty/jxls/jxls-core-1.0.1.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/thirdparty/mina/mina-core-2.0.13.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/thirdparty/mina/slf4j-api-1.7.13.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/thirdparty/mina/slf4j-simple-1.7.13.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/own/BinaryTags.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/lib/own/CommonUtils.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/bin/Core.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/bin/Datamodel.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/bin/Modules.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/bin/Reports.jar:/home/jskonst/workspace/Altsoft/PlatypusJS/application/bin/Server.jar com.eas.server.ServerMain -datasource eas -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser eas -dbpassword eas -dbschema EAS -datasource easHR -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser hr -dbpassword hr -dbschema HR -appelement start.js -url file:///home/jskonst/workspace/Altsoft/PlatypusTests/ -iface 0.0.0.0:8500 -protocols 8500:platypus
ph="/home/jskonst/workspace/Altsoft/PlatypusJS" 
# java -D.level=INFO -Dhandlers=java.util.logging.ConsoleHandler -Djava.util.logging.ConsoleHandler.level=INFO -Djava.util.logging.ConsoleHandler.formatter=com.eas.util.logging.PlatypusFormatter -Djava.util.logging.config.class=com.eas.util.logging.LoggersConfig -cp $ph/application/api:$ph/application/lib/thirdparty/j-interop/j-interop.jar:$ph/application/lib/thirdparty/j-interop/j-interopdeps.jar:$ph/application/lib/thirdparty/j-interop/jcifs-1.2.19.jar:$ph/application/lib/thirdparty/jxls/jxls-core-1.0.1.jar:$ph/application/lib/thirdparty/mina/mina-core-2.0.13.jar:$ph/application/lib/thirdparty/mina/slf4j-api-1.7.13.jar:$ph/application/lib/thirdparty/mina/slf4j-simple-1.7.13.jar:$ph/application/lib/own/BinaryTags.jar:$ph/application/lib/own/CommonUtils.jar:$ph/application/bin/Core.jar:$ph/application/bin/Datamodel.jar:$ph/application/bin/Modules.jar:$ph/application/bin/Reports.jar:$ph/application/bin/Server.jar com.eas.server.ServerMain -datasource eas -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser eas -dbpassword eas -dbschema EAS -datasource easHR -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser hr -dbpassword hr -dbschema HR -appelement start.js -url file:///home/jskonst/workspace/Altsoft/PlatypusTests/ -iface 0.0.0.0:8500 -protocols 8500:platypus

# java -D.level=INFO -Dhandlers=java.util.logging.ConsoleHandler -Djava.util.logging.ConsoleHandler.level=INFO -Djava.util.logging.ConsoleHandler.formatter=com.eas.util.logging.PlatypusFormatter -Djava.util.logging.config.class=com.eas.util.logging.LoggersConfig -cp $ph/application/api:$ph/application/bin/*:$ph/application/bin/Server.jar com.eas.server.ServerMain -datasource eas -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser eas -dbpassword eas -dbschema EAS -datasource easHR -dburl jdbc:oracle:thin:@asvr:1521:adb -dbuser hr -dbpassword hr -dbschema HR -appelement start.js -url file:///home/jskonst/workspace/Altsoft/PlatypusTests/ -iface 0.0.0.0:8500 -protocols 8500:platypus

java -D.level=INFO -Dhandlers=java.util.logging.ConsoleHandler -Djava.util.logging.ConsoleHandler.level=INFO -Djava.util.logging.ConsoleHandler.formatter=com.eas.util.logging.PlatypusFormatter -Djava.util.logging.config.class=com.eas.util.logging.LoggersConfig -cp $ph/application/api:$ph/application/bin/Server.jar com.eas.server.ServerMain -datasource eas -dburl jdbc:mysql://192.168.10.205:3306/eas -dbuser test2 -dbpassword test2 -dbschema EAS -datasource easHR -dburl jdbc:mysql://192.168.10.205:3306/hr -dbuser test2 -dbpassword test2 -dbschema hr -appelement start.js -url file:///home/jskonst/workspace/Altsoft/PlatypusTests/ -iface 0.0.0.0:8500 -protocols 8500:platypus 
