/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultingDialog.java
 *
 * Created on 26.11.2010, 10:06:16
 */
package com.eas.client.model.gui;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 * @author mg
 */
public class ResultingDialog extends javax.swing.JDialog {

    private void fillActionMap() {
        okAction = new OkAction();
        actionMap.put(OkAction.class.getSimpleName(), okAction);
        cancelAction = new CancelAction();
        actionMap.put(CancelAction.class.getSimpleName(), cancelAction);
    }

    private void fillInputMap() {
        InputMap im = pnlContent.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        for (Object actionKey : actionMap.allKeys()) {
            Action action = actionMap.get(actionKey);
            Object acc = action.getValue(Action.ACCELERATOR_KEY);
            if (acc instanceof KeyStroke) {
                im.put((KeyStroke) acc, actionKey);
            }
        }
    }

    public class OkAction extends AbstractAction {

        public OkAction() {
            super();
            putValue(Action.NAME, DatamodelDesignUtils.getLocalizedString("Ok"));
            putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0));
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            ok = true;
            setVisible(false);
            dispose();
            if (okActionListener != null) {
                okActionListener.actionPerformed(e);
            }
        }
    }

    public class CancelAction extends AbstractAction {

        public CancelAction() {
            super();
            putValue(Action.NAME, DatamodelDesignUtils.getLocalizedString("Cancel"));
            putValue(Action.ACCELERATOR_KEY, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0));
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            ok = false;
            setVisible(false);
            dispose();
        }
    }
    protected ActionMap actionMap = new ActionMap();
    protected Action okAction;
    protected ActionListener okActionListener;
    protected Action cancelAction;
    protected boolean ok = false;

    public ResultingDialog(Window aParent, String aTitle, Container aView) {
        this(null, aParent, aTitle, aView);
    }
    /**
     * Creates new form ResultingDialog
     */
    public ResultingDialog(ActionListener aOkActionListener, Window parent, String aTitle, Container aView) {
        super(parent, aTitle, ModalityType.APPLICATION_MODAL);
        okActionListener = aOkActionListener;
        fillActionMap();
        initComponents();
        fillInputMap();
        pnlContent.setActionMap(actionMap);
        if (aView != null) {
            pnlContent.add(aView, BorderLayout.CENTER);
        }
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
    }

    public boolean isOk() {
        return ok;
    }

    public Action getOkAction() {
        return okAction;
    }

    public Action getCancelAction() {
        return cancelAction;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlContent.setLayout(new java.awt.BorderLayout());

        btnOk.setAction(actionMap.get(OkAction.class.getSimpleName()));
        btnOk.setText(DatamodelDesignUtils.getLocalizedString("Ok")); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setAction(actionMap.get(CancelAction.class.getSimpleName()));
        btnCancel.setText(DatamodelDesignUtils.getLocalizedString("Cancel")); // NOI18N

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk)))
        );

        pnlContent.add(pnlBottom, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResultingDialog dialog = new ResultingDialog(new javax.swing.JFrame(), "Test", null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
