/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eas.metadata.gui;

import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author vy
 */
public class AddDatabaseSettingsForm extends javax.swing.JDialog {

    private String fileName;
    private Map<String, String[]> databaseSettings;
    String names[];
    private boolean changed = false;
    private JComboBox databaseList;
    // localized vars
    private String errorSettingsMessage;
    private String errorSettingsTitle;

    /**
     * Creates new form AddDatabaseSettingsForm
     */
    public AddDatabaseSettingsForm(java.awt.Frame parent, boolean modal, String aFileName, Map<String, String[]> aDatabaseSettings, JComboBox aDatabaseList, String aUrl, String aSchema, String aUser, String aPassword) {
        super(parent, modal);
        initComponents();
        initLocalizedNames();
        fileName = aFileName;
        databaseSettings = aDatabaseSettings;
        databaseList = aDatabaseList;
        fldUrl.setText(aUrl);
        fldSchema.setText(aSchema);
        fldUser.setText(aUser);
        fldPassword.setText(aPassword);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public boolean isChanged() {
        return changed;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSettingName = new javax.swing.JLabel();
        fldSettingName = new javax.swing.JTextField();
        lbUrl = new javax.swing.JLabel();
        fldUrl = new javax.swing.JTextField();
        lbSchema = new javax.swing.JLabel();
        fldSchema = new javax.swing.JTextField();
        lbUser = new javax.swing.JLabel();
        fldUser = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        fldPassword = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/eas/metadata/gui/Bundle"); // NOI18N
        setTitle(bundle.getString("AddDatabaseSettingsForm.title")); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbSettingName.setText(bundle.getString("AddDatabaseSettingsForm.lbSettingName.text")); // NOI18N

        fldSettingName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fldSettingNameKeyReleased(evt);
            }
        });

        lbUrl.setText(bundle.getString("AddDatabaseSettingsForm.lbUrl.text")); // NOI18N

        lbSchema.setText(bundle.getString("AddDatabaseSettingsForm.lbSchema.text")); // NOI18N

        lbUser.setText(bundle.getString("AddDatabaseSettingsForm.lbUser.text")); // NOI18N

        lbPassword.setText(bundle.getString("AddDatabaseSettingsForm.lbPassword.text")); // NOI18N

        btnCancel.setText(bundle.getString("AddDatabaseSettingsForm.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setText(bundle.getString("AddDatabaseSettingsForm.btnSave.text")); // NOI18N
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSettingName)
                    .addComponent(lbUrl)
                    .addComponent(lbSchema)
                    .addComponent(lbUser)
                    .addComponent(lbPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(fldUser)
                    .addComponent(fldSchema)
                    .addComponent(fldUrl)
                    .addComponent(fldSettingName))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSettingName)
                    .addComponent(fldSettingName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUrl)
                    .addComponent(fldUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSchema)
                    .addComponent(fldSchema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUser)
                    .addComponent(fldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassword)
                    .addComponent(fldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initLocalizedNames() {
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/eas/metadata/gui/Bundle");
        errorSettingsMessage = bundle.getString("AddDatabaseSettingsForm.MessageDialog.ErrorSettings.message");
        errorSettingsTitle = bundle.getString("AddDatabaseSettingsForm.MessageDialog.ErrorSettings.title");
    }    

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String text = fldSettingName.getText();
        assert databaseList != null;
        if (!text.isEmpty()) {
            if (!databaseSettings.containsKey(text)) {
                String[] setting = new String[MetadataSynchronizerForm.DATABASE_PROPERTIES_SIZE];
                setting[MetadataSynchronizerForm.DATABASE_PROPERTIES_URL_INDEX] = fldUrl.getText();
                setting[MetadataSynchronizerForm.DATABASE_PROPERTIES_SCHEMA_INDEX] = fldSchema.getText();
                setting[MetadataSynchronizerForm.DATABASE_PROPERTIES_USER_INDEX] = fldUser.getText();
                setting[MetadataSynchronizerForm.DATABASE_PROPERTIES_PASSWORD_INDEX] = new String(fldPassword.getPassword());
                databaseSettings.put(text, setting);
                databaseList.addItem(text);
                changed = true;
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, errorSettingsMessage, errorSettingsTitle, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            btnSave.setEnabled(false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void fldSettingNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldSettingNameKeyReleased
        btnSave.setEnabled(!fldSettingName.getText().isEmpty());
        btnSave.repaint();
    }//GEN-LAST:event_fldSettingNameKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JTextField fldSchema;
    private javax.swing.JTextField fldSettingName;
    private javax.swing.JTextField fldUrl;
    private javax.swing.JTextField fldUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbSchema;
    private javax.swing.JLabel lbSettingName;
    private javax.swing.JLabel lbUrl;
    private javax.swing.JLabel lbUser;
    // End of variables declaration//GEN-END:variables
}
