/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ForeignKeySettingsDialog.java
 *
 * Created on 15.10.2009, 13:50:40
 */
package com.eas.client.dbstructure.gui.view;

import com.eas.client.dbstructure.DbStructureUtils;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;

/**
 *
 * @author mg
 */
public class ForeignKeySettingsDialog extends javax.swing.JDialog {

    protected class OkAction extends AbstractAction {

        public void actionPerformed(ActionEvent e) {
            String constraintName = view.getConstraintName();
            if (constraintName != null && !constraintName.isEmpty()) {
                okClose = true;
                dispose();
            } else {
                view.focusConstraintName();
            }
        }
    }

    protected class CancelAction extends AbstractAction {

        public void actionPerformed(ActionEvent e) {
            okClose = false;
            dispose();
        }
    }
    protected boolean okClose = false;
    protected ForeignKeySettingsView view = null;

    /** Creates new form ForeignKeySettingsDialog */
    public ForeignKeySettingsDialog(Frame parent, ForeignKeySettingsView aView, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().add(aView, BorderLayout.CENTER);
        view = aView;
    }

    public boolean isOkClose() {
        return okClose;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottomPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(DbStructureUtils.getString("ForeignKeySettingsDialogTitle")); // NOI18N
        setLocationByPlatform(true);

        bottomPanel.setPreferredSize(new java.awt.Dimension(245, 45));

        btnCancel.setAction(new CancelAction());
        btnCancel.setText(DbStructureUtils.getString("btnCancel")); // NOI18N

        btnOk.setAction(new OkAction());
        btnOk.setText(DbStructureUtils.getString("btnOk")); // NOI18N
        btnOk.setPreferredSize(btnCancel.getPreferredSize());

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    // End of variables declaration//GEN-END:variables
}
