/**
 * 
 * @author mg
 * @name get_query
 */
SELECT GOODORDER.ORDER_ID, T1.AMOUNT, CUSTOMER.CUSTOMER_NAME FROM GOODORDER T1 INNER JOIN CUSTOMER ON (GOODORDER.CUSTOMER=CUSTOMER.CUSTOMER_ID) AND (GOODORDER.AMOUNT>CUSTOMER.CUSTOMER_NAME) WHERE AMOUNT=:p1
