/**
 * 
 * @author mg
 * @name primary_key
 */
SELECT T_MTD_MDCHNGLOG_2.MDLOG_ID, T_MTD_MDCHNGLOG_2.OPDATE, T_MTD_MDCHNGLOG_2.OPSESSION_USER, T_MTD_MDCHNGLOG_2.OPHOST, T_MTD_MDCHNGLOG_2.OPTERMINAL, T_MTD_MDCHNGLOG_2.OPTYPE, T_MTD_MDCHNGLOG_2.OPOBJTYPE FROM PUBLIC.MTD_MDCHNGLOG T_MTD_MDCHNGLOG_2