/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuerySettingsVisualPanel.java
 *
 * Created on 25.03.2011, 11:54:03
 */
package com.eas.designer.application.query.templates;

import com.eas.client.settings.DbConnectionSettings;
import com.eas.client.settings.EasSettings;
import com.eas.client.settings.XmlDom2ConnectionSettings;
import com.eas.designer.application.PlatypusUtils;
import com.eas.designer.application.indexer.IndexerQuery;
import com.eas.designer.explorer.FileChooser;
import com.eas.xml.dom.Source2XmlDom;
import java.sql.DriverManager;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.ErrorManager;
import org.openide.WizardDescriptor;
import org.openide.filesystems.FileObject;
import org.openide.util.NbBundle;

/**
 *
 * @author mg
 */
public class QuerySettingsVisualPanel extends javax.swing.JPanel {

    protected NewQueryWizardSettingsPanel panel;
    protected FileObject connectionFile;
    protected DefaultComboBoxModel<String> schemasModel;

    /** Creates new form QuerySettingsVisualPanel */
    public QuerySettingsVisualPanel(NewQueryWizardSettingsPanel aWizardStep) {
        initComponents();
        panel = aWizardStep;
    }

    protected DbConnectionSettings readSettings(FileObject aFile) throws Exception {
        EasSettings settings = null;
        if (aFile != null) {
            String sContent = aFile.asText(PlatypusUtils.COMMON_ENCODING_NAME);
            settings = XmlDom2ConnectionSettings.document2Settings(Source2XmlDom.transform(sContent));
        } else {
            settings = panel.getProject().getClient().getSettings();
        }
        assert settings instanceof DbConnectionSettings : "Platypus application designer must work only in two tier mode.";
        return (DbConnectionSettings) settings;
    }

    protected void refreshButtons() {
        if (connectionFile == null) {
            btnApplicationConnection.setSelected(true);
        } else {
            btnSpecificConnection.setSelected(true);
        }
    }

    public void refreshControls() throws Exception {
        String connectionId = null;
        if (connectionFile != null) {
            connectionId = IndexerQuery.file2AppElementId(connectionFile);
        }
        if (connectionId == null) {
            txtConnection.setText(panel.getProject().getDisplayName());
        } else {
            assert connectionFile != null;
            txtConnection.setText(connectionFile.getName());
        }
        refreshButtons();
    }

    public boolean valid(WizardDescriptor wd) throws Exception {
        FileObject lconnectionFile = (FileObject) wd.getProperty(NewQueryWizardSettingsPanel.CONNECTION_PROP_NAME);
        if (lconnectionFile != null && !panel.isConnectionElement(lconnectionFile)) {
            wd.putProperty(WizardDescriptor.PROP_ERROR_MESSAGE, NbBundle.getMessage(QuerySettingsVisualPanel.class, "nonConnectionFile"));
            return false;
        }
        wd.putProperty(WizardDescriptor.PROP_INFO_MESSAGE, NbBundle.getMessage(QuerySettingsVisualPanel.class, "readyForNextStep"));
        return true;
    }

    void store(WizardDescriptor wd) throws Exception {
        wd.putProperty(NewQueryWizardSettingsPanel.CONNECTION_PROP_NAME, connectionFile);
    }

    void read(WizardDescriptor wd) throws Exception {
        connectionFile = (FileObject) wd.getProperty(NewQueryWizardSettingsPanel.CONNECTION_PROP_NAME);
        refreshControls();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupConnectionType = new javax.swing.ButtonGroup();
        lblConnection = new javax.swing.JLabel();
        txtConnection = new javax.swing.JTextField();
        btnApplicationConnection = new javax.swing.JToggleButton();
        btnSpecificConnection = new javax.swing.JToggleButton();

        lblConnection.setText(org.openide.util.NbBundle.getMessage(QuerySettingsVisualPanel.class, "QuerySettingsVisualPanel.lblConnection.text")); // NOI18N

        txtConnection.setEditable(false);

        groupConnectionType.add(btnApplicationConnection);
        btnApplicationConnection.setSelected(true);
        btnApplicationConnection.setText(org.openide.util.NbBundle.getMessage(QuerySettingsVisualPanel.class, "QuerySettingsVisualPanel.btnApplicationConnection.text")); // NOI18N
        btnApplicationConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplicationConnectionActionPerformed(evt);
            }
        });

        groupConnectionType.add(btnSpecificConnection);
        btnSpecificConnection.setText(org.openide.util.NbBundle.getMessage(QuerySettingsVisualPanel.class, "QuerySettingsVisualPanel.btnSpecificConnection.text")); // NOI18N
        btnSpecificConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpecificConnectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConnection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtConnection, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApplicationConnection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSpecificConnection)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConnection)
                    .addComponent(txtConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplicationConnection)
                    .addComponent(btnSpecificConnection))
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpecificConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpecificConnectionActionPerformed
        try {
            selectNewConnection();
        } catch (Exception ex) {
            ErrorManager.getDefault().notify(ex);
        }
    }//GEN-LAST:event_btnSpecificConnectionActionPerformed

    private void btnApplicationConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplicationConnectionActionPerformed
        try {
            connectionFile = null;
            refreshControls();
        } catch (Exception ex) {
            ErrorManager.getDefault().notify(ex);
        }
    }//GEN-LAST:event_btnApplicationConnectionActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnApplicationConnection;
    private javax.swing.JToggleButton btnSpecificConnection;
    private javax.swing.ButtonGroup groupConnectionType;
    private javax.swing.JLabel lblConnection;
    private javax.swing.JTextField txtConnection;
    // End of variables declaration//GEN-END:variables

    private void selectNewConnection() throws Exception {
        Set<String> allowedMimeTypes = new HashSet<>();
        allowedMimeTypes.add("text/connection+xml");
        FileObject fo = FileChooser.selectFile(panel.getProject().getSrcRoot(), connectionFile, allowedMimeTypes);
        if (fo != connectionFile) {
            // let's test connection capability
            try {
                DbConnectionSettings settings = readSettings(connectionFile);
                java.sql.Connection conn = DriverManager.getConnection(settings.getUrl(), settings.getInfo());
                conn.close();
            } catch (Exception ex) {
                refreshButtons();
                DialogDescriptor.Message dd = new DialogDescriptor.Message(ex.getMessage(), DialogDescriptor.Message.ERROR_MESSAGE);
                DialogDisplayer.getDefault().notify(dd);
                return;
            }
            connectionFile = fo;
            refreshControls();
        }
    }
}
