/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bearsoft.rowset.resourcepool;

import java.sql.*;
import java.util.*;
import java.util.Map.Entry;
import java.util.concurrent.Executor;

/**
 *
 * @author mg
 */
public class BearDatabaseConnection implements Connection {

    protected final Map<String, PreparedStatement> stmts = new HashMap<>();
    protected final Map<String, CallableStatement> calls = new HashMap<>();
    protected ResourcePool<BearDatabaseConnection> connectionsPool;
    protected Connection delegate;
    protected int maxStatements = Integer.MAX_VALUE;

    public BearDatabaseConnection(int aMaxStatetments, Connection aDelegate, ResourcePool<BearDatabaseConnection> aPool) throws Exception {
        super();
        delegate = aDelegate;
        connectionsPool = aPool;
        maxStatements = aMaxStatetments;
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        return delegate.getNetworkTimeout();
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
        delegate.setNetworkTimeout(executor, milliseconds);
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        delegate.abort(executor);
    }

    @Override
    public String getSchema() throws SQLException {
        return delegate.getSchema();
    }

    @Override
    public void setSchema(String schema) throws SQLException {
        delegate.setSchema(schema);
    }

    public synchronized void returnPreparedStatement(String aSqlClause, PreparedStatement aStatement) {
        stmts.put(aSqlClause, aStatement);
    }

    public synchronized void returnCallableStatement(String aSqlClause, CallableStatement aStatement) {
        calls.put(aSqlClause, aStatement);
    }

    protected static <S extends PreparedStatement> int riddleStatements(Map<String, S> aStmts) throws SQLException {
        Set<String> toRemove = new HashSet<>();
        for (Entry<String, S> stmt : aStmts.entrySet()) {
            if (stmt.getValue() != null) {
                stmt.getValue().close();
                toRemove.add(stmt.getKey());
            }
        }
        for (String callKey : toRemove) {
            aStmts.remove(callKey);
        }
        return toRemove.size();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        PreparedStatement stmt = tryPrepareStatement(sql);
        while (stmt == null && Thread.currentThread().isAlive()) {
            waitSome(BearResourcePool.WAIT_TIMEOUT);
            stmt = tryPrepareStatement(sql);
        }
        return stmt;
    }

    public synchronized PreparedStatement tryPrepareStatement(String sql) throws SQLException {
        BearPreparedStatement stmt = null;
        if (!stmts.containsKey(sql)) {
            shrinkCallsAndStatements();
            if (stmts.size() + calls.size() >= maxStatements) {
                // nothing has changed. It's still to large, so return null;
                return null;
            }
            stmt = wrapPreparedStatement(sql, delegate.prepareStatement(sql));
        } else {
            PreparedStatement llstmt = stmts.get(sql);
            if (llstmt != null) {
                stmt = wrapPreparedStatement(sql, llstmt);
            }// else ... possible only in multithreaded environment
        }
        stmts.put(sql, null);
        return stmt;
    }

    private void shrinkCallsAndStatements() throws SQLException {
        // we are about to add element into map
        // let's check if it is possible
        if (stmts.size() + calls.size() >= maxStatements) {
            riddleStatements(stmts);
            riddleStatements(calls);
        }
    }

    protected BearCallableStatement wrapPrearedCall(String aSql, CallableStatement aCall) {
        return new BearCallableStatement(aSql, aCall, this);
    }

    protected BearPreparedStatement wrapPreparedStatement(String aSql, PreparedStatement aStatement) throws SQLException {
        return new BearPreparedStatement(aSql, aStatement, this);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return prepareCall(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return prepareCall(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        CallableStatement stmt = tryPrepareCall(sql);
        while (stmt == null && Thread.currentThread().isAlive()) {
            waitSome(15);
            stmt = tryPrepareCall(sql);
        }
        return stmt;
    }

    private void waitSome(int aTimeout) throws SQLException {
        try {
            Thread.sleep(aTimeout);
        } catch (Exception ex) {
            Thread.currentThread().interrupt();
            throw new SQLException(ex);
        }
    }

    public synchronized CallableStatement tryPrepareCall(String sql) throws SQLException {
        BearCallableStatement stmt = null;
        if (!calls.containsKey(sql)) {
            shrinkCallsAndStatements();
            if (stmts.size() + calls.size() >= maxStatements) {
                // nothing has changed. It's still to big, so return null;
                return null;
            }
            stmt = wrapPrearedCall(sql, delegate.prepareCall(sql));
        } else {
            CallableStatement llCall = calls.get(sql);
            if (llCall != null) {
                stmt = wrapPrearedCall(sql, llCall);
            }// else ... possible only in multithreaded environment
        }
        calls.put(sql, null);
        return stmt;
    }

    @Override
    public void close() throws SQLException {
        connectionsPool.returnResource(this);
    }

    @Override
    public boolean isClosed() throws SQLException {
        return delegate == null || delegate.isClosed();
    }

    /* 
     * Delegating section
     */
    /**
     * @inheritDoc
     */
    @Override
    public Statement createStatement() throws SQLException {
        checkClosed();
        return delegate.createStatement();
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        checkClosed();
        return delegate.nativeSQL(sql);
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        checkClosed();
        delegate.setAutoCommit(autoCommit);
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        checkClosed();
        return delegate.getAutoCommit();
    }

    @Override
    public void commit() throws SQLException {
        checkClosed();
        synchronized (this) {
            riddleStatements(stmts);
            riddleStatements(calls);
        }
        delegate.commit();
    }

    @Override
    public void rollback() throws SQLException {
        checkClosed();
        delegate.rollback();
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        checkClosed();
        return delegate.getMetaData();
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        checkClosed();
        delegate.setReadOnly(readOnly);
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        checkClosed();
        return delegate.isReadOnly();
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        checkClosed();
        delegate.setCatalog(catalog);
    }

    @Override
    public String getCatalog() throws SQLException {
        checkClosed();
        return delegate.getCatalog();
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        delegate.setTransactionIsolation(level);
        checkClosed();
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        checkClosed();
        return delegate.getTransactionIsolation();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        checkClosed();
        return delegate.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        checkClosed();
        delegate.clearWarnings();
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        checkClosed();
        return delegate.createStatement(resultSetType, resultSetConcurrency);
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        checkClosed();
        return delegate.getTypeMap();
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        checkClosed();
        delegate.setTypeMap(map);
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        checkClosed();
        delegate.setHoldability(holdability);
    }

    @Override
    public int getHoldability() throws SQLException {
        checkClosed();
        return delegate.getHoldability();
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        checkClosed();
        return delegate.setSavepoint();
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        checkClosed();
        return delegate.setSavepoint(name);
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        checkClosed();
        delegate.rollback(savepoint);
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        checkClosed();
        delegate.releaseSavepoint(savepoint);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        checkClosed();
        return delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public Clob createClob() throws SQLException {
        checkClosed();
        return delegate.createClob();
    }

    @Override
    public Blob createBlob() throws SQLException {
        checkClosed();
        return delegate.createBlob();
    }

    @Override
    public NClob createNClob() throws SQLException {
        checkClosed();
        return delegate.createNClob();
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        checkClosed();
        return delegate.createSQLXML();
    }

    @Override
    public boolean isValid(int timeout) throws SQLException {
        checkClosed();
        return delegate.isValid(timeout);
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        try {
            checkClosed();
            delegate.setClientInfo(name, value);
        } catch (SQLException ex) {
            Map<String, ClientInfoStatus> props = new HashMap<>();
            props.put(name, ClientInfoStatus.REASON_UNKNOWN);
            throw new SQLClientInfoException(props, ex);
        }
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        try {
            checkClosed();
            delegate.setClientInfo(properties);
        } catch (SQLException ex) {
            Map<String, ClientInfoStatus> props = new HashMap<>();
            for (Object key : properties.keySet()) {
                props.put(String.valueOf(key), ClientInfoStatus.REASON_UNKNOWN);
            }
            throw new SQLClientInfoException(props, ex);
        }
    }

    @Override
    public String getClientInfo(String name) throws SQLException {
        checkClosed();
        return delegate.getClientInfo(name);
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        checkClosed();
        return delegate.getClientInfo();
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        checkClosed();
        return delegate.createArrayOf(typeName, elements);
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        checkClosed();
        return delegate.createStruct(typeName, attributes);
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        checkClosed();
        if (isWrapperFor(iface)) {
            return (T) delegate;
        } else {
            return null;
        }
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        checkClosed();
        return iface.isAssignableFrom(delegate.getClass());
    }

    private void checkClosed() throws SQLException {
        if (delegate == null) {
            throw new SQLException("Connection already closed.");
        }
    }
}
