/* Generated By:JavaCC: Do not edit this line. CCJSqlParserConstants.java */
/* ================================================================
 * JSQLParser : java based sql parser 
 * ================================================================
 *
 * Project Info:  http://jsqlparser.sourceforge.net
 * Project Lead:  Leonardo Francalanci (leoonardoo@yahoo.it);
 *
 * (C) Copyright 2004, by Leonardo Francalanci
 *
 * This library is free software; you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free Software Foundation;
 * either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307, USA.
 */


package net.sf.jsqlparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCJSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_AS = 6;
  /** RegularExpression Id. */
  int K_START = 7;
  /** RegularExpression Id. */
  int K_CONNECT = 8;
  /** RegularExpression Id. */
  int K_NOCYCLE = 9;
  /** RegularExpression Id. */
  int K_PRIOR = 10;
  /** RegularExpression Id. */
  int K_BY = 11;
  /** RegularExpression Id. */
  int K_DO = 12;
  /** RegularExpression Id. */
  int K_IS = 13;
  /** RegularExpression Id. */
  int K_IN = 14;
  /** RegularExpression Id. */
  int K_OR = 15;
  /** RegularExpression Id. */
  int K_ON = 16;
  /** RegularExpression Id. */
  int K_ALL = 17;
  /** RegularExpression Id. */
  int K_AND = 18;
  /** RegularExpression Id. */
  int K_ANY = 19;
  /** RegularExpression Id. */
  int K_KEY = 20;
  /** RegularExpression Id. */
  int K_NOT = 21;
  /** RegularExpression Id. */
  int K_SET = 22;
  /** RegularExpression Id. */
  int K_ASC = 23;
  /** RegularExpression Id. */
  int K_TOP = 24;
  /** RegularExpression Id. */
  int K_END = 25;
  /** RegularExpression Id. */
  int K_DESC = 26;
  /** RegularExpression Id. */
  int K_INTO = 27;
  /** RegularExpression Id. */
  int K_NULL = 28;
  /** RegularExpression Id. */
  int K_LIKE = 29;
  /** RegularExpression Id. */
  int K_DROP = 30;
  /** RegularExpression Id. */
  int K_JOIN = 31;
  /** RegularExpression Id. */
  int K_LEFT = 32;
  /** RegularExpression Id. */
  int K_FROM = 33;
  /** RegularExpression Id. */
  int K_OPEN = 34;
  /** RegularExpression Id. */
  int K_CASE = 35;
  /** RegularExpression Id. */
  int K_WHEN = 36;
  /** RegularExpression Id. */
  int K_THEN = 37;
  /** RegularExpression Id. */
  int K_ELSE = 38;
  /** RegularExpression Id. */
  int K_SOME = 39;
  /** RegularExpression Id. */
  int K_FULL = 40;
  /** RegularExpression Id. */
  int K_WITH = 41;
  /** RegularExpression Id. */
  int K_TABLE = 42;
  /** RegularExpression Id. */
  int K_WHERE = 43;
  /** RegularExpression Id. */
  int K_USING = 44;
  /** RegularExpression Id. */
  int K_UNION = 45;
  /** RegularExpression Id. */
  int K_EXCEPT = 46;
  /** RegularExpression Id. */
  int K_GROUP = 47;
  /** RegularExpression Id. */
  int K_BEGIN = 48;
  /** RegularExpression Id. */
  int K_INDEX = 49;
  /** RegularExpression Id. */
  int K_INNER = 50;
  /** RegularExpression Id. */
  int K_LIMIT = 51;
  /** RegularExpression Id. */
  int K_OUTER = 52;
  /** RegularExpression Id. */
  int K_ORDER = 53;
  /** RegularExpression Id. */
  int K_RIGHT = 54;
  /** RegularExpression Id. */
  int K_DELETE = 55;
  /** RegularExpression Id. */
  int K_CREATE = 56;
  /** RegularExpression Id. */
  int K_SELECT = 57;
  /** RegularExpression Id. */
  int K_OFFSET = 58;
  /** RegularExpression Id. */
  int K_EXISTS = 59;
  /** RegularExpression Id. */
  int K_HAVING = 60;
  /** RegularExpression Id. */
  int K_INSERT = 61;
  /** RegularExpression Id. */
  int K_UPDATE = 62;
  /** RegularExpression Id. */
  int K_VALUES = 63;
  /** RegularExpression Id. */
  int K_ESCAPE = 64;
  /** RegularExpression Id. */
  int K_PRIMARY = 65;
  /** RegularExpression Id. */
  int K_NATURAL = 66;
  /** RegularExpression Id. */
  int K_REPLACE = 67;
  /** RegularExpression Id. */
  int K_BETWEEN = 68;
  /** RegularExpression Id. */
  int K_TRUNCATE = 69;
  /** RegularExpression Id. */
  int K_DISTINCT = 70;
  /** RegularExpression Id. */
  int K_INTERSECT = 71;
  /** RegularExpression Id. */
  int S_DOUBLE = 72;
  /** RegularExpression Id. */
  int S_INTEGER = 73;
  /** RegularExpression Id. */
  int DIGIT = 74;
  /** RegularExpression Id. */
  int S_CROSS = 75;
  /** RegularExpression Id. */
  int LINE_COMMENT = 76;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 77;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 78;
  /** RegularExpression Id. */
  int LETTER = 79;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 80;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 81;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 82;
  /** RegularExpression Id. */
  int SEMICOLON = 83;
  /** RegularExpression Id. */
  int PERCENT = 84;
  /** RegularExpression Id. */
  int LSQPAREN = 85;
  /** RegularExpression Id. */
  int RSQPAREN = 86;
  /** RegularExpression Id. */
  int TILDA = 87;
  /** RegularExpression Id. */
  int EXCLAMATION = 88;
  /** RegularExpression Id. */
  int AT = 89;
  /** RegularExpression Id. */
  int DOLLAR = 90;
  /** RegularExpression Id. */
  int SINGLEQUOTE = 91;
  /** RegularExpression Id. */
  int DOUBLEQUOTE = 92;
  /** RegularExpression Id. */
  int BACKQUOTE = 93;
  /** RegularExpression Id. */
  int BACKSLASH = 94;
  /** RegularExpression Id. */
  int EQUALS = 95;
  /** RegularExpression Id. */
  int COMMA = 96;
  /** RegularExpression Id. */
  int LPAREN = 97;
  /** RegularExpression Id. */
  int RPAREN = 98;
  /** RegularExpression Id. */
  int DOT = 99;
  /** RegularExpression Id. */
  int MULTIPLY = 100;
  /** RegularExpression Id. */
  int HOOK = 101;
  /** RegularExpression Id. */
  int GT = 102;
  /** RegularExpression Id. */
  int LT = 103;
  /** RegularExpression Id. */
  int GE = 104;
  /** RegularExpression Id. */
  int LE = 105;
  /** RegularExpression Id. */
  int NOTEQUAL1 = 106;
  /** RegularExpression Id. */
  int NOTEQUAL2 = 107;
  /** RegularExpression Id. */
  int ATAT = 108;
  /** RegularExpression Id. */
  int OR = 109;
  /** RegularExpression Id. */
  int BITWISEOR = 110;
  /** RegularExpression Id. */
  int BITWISEAND = 111;
  /** RegularExpression Id. */
  int ADD = 112;
  /** RegularExpression Id. */
  int MINUS = 113;
  /** RegularExpression Id. */
  int DIVIDE = 114;
  /** RegularExpression Id. */
  int XOR = 115;
  /** RegularExpression Id. */
  int COLON = 116;
  /** RegularExpression Id. */
  int DATELITERAL = 117;
  /** RegularExpression Id. */
  int TIMELITERAL = 118;
  /** RegularExpression Id. */
  int TIMESTAMPLITERAL = 119;
  /** RegularExpression Id. */
  int ESCAPEDLITEARL = 120;
  /** RegularExpression Id. */
  int LITERALBEGIN = 121;
  /** RegularExpression Id. */
  int LITERALEND = 122;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"AS\"",
    "\"START\"",
    "\"CONNECT\"",
    "\"NOCYCLE\"",
    "\"PRIOR\"",
    "\"BY\"",
    "\"DO\"",
    "\"IS\"",
    "\"IN\"",
    "\"OR\"",
    "\"ON\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"KEY\"",
    "\"NOT\"",
    "\"SET\"",
    "\"ASC\"",
    "\"TOP\"",
    "\"END\"",
    "\"DESC\"",
    "\"INTO\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"DROP\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"FROM\"",
    "\"OPEN\"",
    "\"CASE\"",
    "\"WHEN\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"SOME\"",
    "\"FULL\"",
    "\"WITH\"",
    "\"TABLE\"",
    "\"WHERE\"",
    "\"USING\"",
    "\"UNION\"",
    "\"EXCEPT\"",
    "\"GROUP\"",
    "\"BEGIN\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"LIMIT\"",
    "\"OUTER\"",
    "\"ORDER\"",
    "\"RIGHT\"",
    "\"DELETE\"",
    "\"CREATE\"",
    "\"SELECT\"",
    "\"OFFSET\"",
    "\"EXISTS\"",
    "\"HAVING\"",
    "\"INSERT\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"ESCAPE\"",
    "\"PRIMARY\"",
    "\"NATURAL\"",
    "\"REPLACE\"",
    "\"BETWEEN\"",
    "\"TRUNCATE\"",
    "\"DISTINCT\"",
    "\"INTERSECT\"",
    "<S_DOUBLE>",
    "<S_INTEGER>",
    "<DIGIT>",
    "\"#\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\";\"",
    "\"%\"",
    "\"[\"",
    "\"]\"",
    "\"~\"",
    "\"!\"",
    "\"@\"",
    "\"$\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"`\"",
    "\"\\\\\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"*\"",
    "\"?\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"!=\"",
    "\"@@\"",
    "\"||\"",
    "\"|\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"^\"",
    "\":\"",
    "\"{d\"",
    "\"{t\"",
    "\"{ts\"",
    "\"{fn\"",
    "\"{\"",
    "\"}\"",
  };

}
