/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eas.designer.explorer.project.ui;

import com.eas.designer.application.utils.DatabaseServerType;
import javax.swing.DefaultComboBoxModel;
import org.openide.util.NbBundle;

/**
 *
 * @author vv
 */
public class BuildJdbcUrlPanel extends javax.swing.JPanel {

    private static final String LOCAL_HOSTNAME = "localhost"; //NOI18N
    
    public String getJdbcUrl() {
        return getCurrentServerType().buildUrl(txtHost.getText(), (int)spPort.getValue(), txtDatabaseName.getText());
    }
    
    /**
     * Creates new form BuildJdbcUrlPanel
     */
    public BuildJdbcUrlPanel() {
        initComponents();
        txtHost.setText(LOCAL_HOSTNAME);
        setupControls();
    }
    
    private void setupControls() {
        spPort.setValue(getCurrentServerType().defaultPort);
        txtDatabaseName.setText(getCurrentServerType().databaseTemplate);
        lblInfo.setText(getCurrentServerType().info);
    }
    
    private DatabaseServerType getCurrentServerType() {
        return (DatabaseServerType)cbServer.getSelectedItem();
    }
    
    public String getTitle() {
        return NbBundle.getMessage(BuildJdbcUrlPanel.class, "ProjectDatabaseCustomizer.btnBuildJdbcUrl.text");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbServer = new javax.swing.JComboBox();
        lblServer = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        txtHost = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        spPort = new javax.swing.JSpinner();
        lblDatabaseName = new javax.swing.JLabel();
        txtDatabaseName = new javax.swing.JTextField();
        lblInfo = new javax.swing.JLabel();

        cbServer.setModel(new DefaultComboBoxModel(com.eas.designer.application.utils.DatabaseServerType.values()));
        cbServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServerActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblServer, org.openide.util.NbBundle.getMessage(BuildJdbcUrlPanel.class, "BuildJdbcUrlPanel.lblServer.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblHost, org.openide.util.NbBundle.getMessage(BuildJdbcUrlPanel.class, "BuildJdbcUrlPanel.lblHost.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblPort, org.openide.util.NbBundle.getMessage(BuildJdbcUrlPanel.class, "BuildJdbcUrlPanel.lblPort.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblDatabaseName, org.openide.util.NbBundle.getMessage(BuildJdbcUrlPanel.class, "BuildJdbcUrlPanel.lblDatabaseName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblInfo, org.openide.util.NbBundle.getMessage(BuildJdbcUrlPanel.class, "BuildJdbcUrlPanel.lblInfo.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblServer)
                            .addComponent(lblHost)
                            .addComponent(lblPort)
                            .addComponent(lblDatabaseName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHost)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbServer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spPort, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 176, Short.MAX_VALUE))
                            .addComponent(txtDatabaseName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServer)
                    .addComponent(cbServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPort)
                    .addComponent(spPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatabaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatabaseName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServerActionPerformed
        setupControls();
    }//GEN-LAST:event_cbServerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbServer;
    private javax.swing.JLabel lblDatabaseName;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblServer;
    private javax.swing.JSpinner spPort;
    private javax.swing.JTextField txtDatabaseName;
    private javax.swing.JTextField txtHost;
    // End of variables declaration//GEN-END:variables
}
