/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjectRunningCustomizer.java
 *
 * Created on 17.03.2011, 18:07:31
 */
package com.eas.designer.explorer.project.ui;

import com.eas.client.settings.DbConnectionSettings;
import com.eas.designer.application.HandlerRegistration;
import com.eas.designer.explorer.project.PlatypusProjectImpl;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.util.NbBundle;

/**
 *
 * @author mg
 */
public class ProjectDatabaseCustomizer extends javax.swing.JPanel {

    protected PlatypusProjectImpl project;
    protected transient HandlerRegistration clientChangeListener;

    /**
     * Creates new form ProjectRunningCustomizer
     */
    public ProjectDatabaseCustomizer(PlatypusProjectImpl aProject) throws Exception {
        super();
        initComponents();
        project = aProject;
        assert aProject.getSettings() != null;
        DbConnectionSettings dbSettings = aProject.getSettings().getAppSettings().getDbSettings();
        if (dbSettings != null && dbSettings.getUrl() != null) {
            jdbcUrlTextField.setText(dbSettings.getUrl());
        }
        if (dbSettings != null && dbSettings.getUser() != null) {
            dbUserTextField.setText(dbSettings.getUser());
        }
        if (dbSettings != null && dbSettings.getPassword() != null) {
            dbUserPasswordTextField.setText(dbSettings.getPassword());
        }
        setupComponents();
        clientChangeListener = project.addClientChangeListener(new Runnable() {
            @Override
            public void run() {
                setupComponents();
            }
        });
    }

    @Override
    public void removeNotify() {
        if (clientChangeListener != null) {
            clientChangeListener.remove();
        }
        super.removeNotify();
    }

    private void setupComponents() {
        if (project.getClient() != null) {
            btnTryConnect.setText(NbBundle.getMessage(ProjectDatabaseCustomizer.class, "ProjectDatabaseCustomizer.btnTryConnect.text1"));
        } else {
            btnTryConnect.setText(NbBundle.getMessage(ProjectDatabaseCustomizer.class, "ProjectDatabaseCustomizer.btnTryConnect.text"));
        }
    }

    private void constructConnectionSettings() {
        try {
            DbConnectionSettings dbSettings = new DbConnectionSettings();
            dbSettings.setUrl(jdbcUrlTextField.getText());
            dbSettings.setUser(dbUserTextField.getText());
            dbSettings.setPassword(new String(dbUserPasswordTextField.getPassword()));
            project.getSettings().getAppSettings().setDbSettings(dbSettings);
        } catch (Exception ex) {
            Logger.getLogger(ProjectDatabaseCustomizer.class.getName()).log(Level.WARNING, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdbcUrlLabel = new javax.swing.JLabel();
        jdbcUrlTextField = new javax.swing.JTextField();
        dbUserLabel = new javax.swing.JLabel();
        dbUserTextField = new javax.swing.JTextField();
        dbUserPasswordLabel = new javax.swing.JLabel();
        btnTryConnect = new javax.swing.JButton();
        btnBuildJdbcUrl = new javax.swing.JButton();
        dbUserPasswordTextField = new javax.swing.JPasswordField();

        org.openide.awt.Mnemonics.setLocalizedText(jdbcUrlLabel, org.openide.util.NbBundle.getMessage(ProjectDatabaseCustomizer.class, "ProjectDatabaseCustomizer.jdbcUrlLabel.text")); // NOI18N

        jdbcUrlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdbcUrlTextFieldActionPerformed(evt);
            }
        });
        jdbcUrlTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdbcUrlTextFieldFocusLost(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(dbUserLabel, org.openide.util.NbBundle.getMessage(ProjectDatabaseCustomizer.class, "ProjectDatabaseCustomizer.dbUserLabel.text")); // NOI18N

        dbUserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbUserTextFieldActionPerformed(evt);
            }
        });
        dbUserTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbUserTextFieldFocusLost(evt);
            }
        });

        dbUserPasswordLabel.setText(org.openide.util.NbBundle.getMessage(ProjectDatabaseCustomizer.class, "ProjectDatabaseCustomizer.dbUserPasswordLabel.text")); // NOI18N

        btnTryConnect.setText(org.openide.util.NbBundle.getMessage(ProjectDatabaseCustomizer.class, "ProjectDatabaseCustomizer.btnTryConnect.text")); // NOI18N
        btnTryConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryConnectActionPerformed(evt);
            }
        });

        btnBuildJdbcUrl.setText(org.openide.util.NbBundle.getMessage(ProjectDatabaseCustomizer.class, "ProjectDatabaseCustomizer.btnBuildJdbcUrl.text")); // NOI18N
        btnBuildJdbcUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuildJdbcUrlActionPerformed(evt);
            }
        });

        dbUserPasswordTextField.setText(org.openide.util.NbBundle.getMessage(ProjectDatabaseCustomizer.class, "ProjectDatabaseCustomizer.dbUserPasswordTextField.text")); // NOI18N
        dbUserPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbUserPasswordTextFieldActionPerformed(evt);
            }
        });
        dbUserPasswordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dbUserPasswordTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbUserLabel)
                    .addComponent(jdbcUrlLabel)
                    .addComponent(dbUserPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbUserTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdbcUrlTextField)
                    .addComponent(dbUserPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTryConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuildJdbcUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdbcUrlLabel)
                    .addComponent(jdbcUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuildJdbcUrl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbUserLabel)
                    .addComponent(dbUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbUserPasswordLabel)
                    .addComponent(dbUserPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTryConnect)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTryConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryConnectActionPerformed
        try {
            if (project.getClient() == null) {
                project.startConnecting2db();
            } else {
                project.disconnectFormDb();
            }
        } catch (InterruptedException | ExecutionException ex) {
            Logger.getLogger(ProjectDatabaseCustomizer.class.getName()).log(Level.WARNING, null, ex);
        }
    }//GEN-LAST:event_btnTryConnectActionPerformed

    private void jdbcUrlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdbcUrlTextFieldActionPerformed
        constructConnectionSettings();
    }//GEN-LAST:event_jdbcUrlTextFieldActionPerformed

    private void jdbcUrlTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdbcUrlTextFieldFocusLost
        constructConnectionSettings();
    }//GEN-LAST:event_jdbcUrlTextFieldFocusLost

    private void dbUserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbUserTextFieldActionPerformed
        constructConnectionSettings();
    }//GEN-LAST:event_dbUserTextFieldActionPerformed

    private void dbUserTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbUserTextFieldFocusLost
        constructConnectionSettings();
    }//GEN-LAST:event_dbUserTextFieldFocusLost

    private void btnBuildJdbcUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildJdbcUrlActionPerformed
        BuildJdbcUrlPanel p = new BuildJdbcUrlPanel();
        DialogDescriptor d = new DialogDescriptor(p, p.getTitle());
        Object result = DialogDisplayer.getDefault().notify(d);
        if (DialogDescriptor.OK_OPTION.equals(result)) {
            jdbcUrlTextField.setText(p.getJdbcUrl());
        }
    }//GEN-LAST:event_btnBuildJdbcUrlActionPerformed

    private void dbUserPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbUserPasswordTextFieldActionPerformed
        constructConnectionSettings();
    }//GEN-LAST:event_dbUserPasswordTextFieldActionPerformed

    private void dbUserPasswordTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dbUserPasswordTextFieldFocusLost
        constructConnectionSettings();
    }//GEN-LAST:event_dbUserPasswordTextFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuildJdbcUrl;
    private javax.swing.JButton btnTryConnect;
    private javax.swing.JLabel dbUserLabel;
    private javax.swing.JLabel dbUserPasswordLabel;
    private javax.swing.JPasswordField dbUserPasswordTextField;
    private javax.swing.JTextField dbUserTextField;
    private javax.swing.JLabel jdbcUrlLabel;
    private javax.swing.JTextField jdbcUrlTextField;
    // End of variables declaration//GEN-END:variables
}
