/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectionSettingsDialog.java
 *
 * Created on Jun 25, 2009, 8:49:30 PM
 */
package com.eas.client.login;

import java.awt.event.ActionEvent;
import java.util.ResourceBundle;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author pk
 */
public class ConnectionSettingsDialog extends javax.swing.JDialog {

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private int returnStatus = RET_CANCEL;
    private static final ResourceBundle bundle = ResourceBundle.getBundle("com/eas/client/login/Bundle");
    private AddConnectionAction addConnectionAction = new AddConnectionAction();

    /** Creates new form ConnectionSettingsDialog
     * @param parent
     * @param modal
     */
    public ConnectionSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tfConnectionUrl.requestFocus();
        getRootPane().setDefaultButton(btnOk);
        tfConnectionUrl.getDocument().addDocumentListener(new DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                checkControls();
            }

            public void removeUpdate(DocumentEvent e) {
                checkControls();
            }

            public void changedUpdate(DocumentEvent e) {
                checkControls();
            }
        });
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        checkControls();
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfConnectionUrl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfSchema = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("ConnectionSettingsDialog.title")); // NOI18N
        setLocationByPlatform(true);

        btnCancel.setText(bundle.getString("Dialog.CancelButton.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setAction(addConnectionAction);
        btnOk.setText(bundle.getString("Dialog.OKButton.text")); // NOI18N

        jLabel4.setLabelFor(tfName);
        jLabel4.setText(bundle.getString("ConnectionSettingsDialog.lblConnectionTitle.text")); // NOI18N

        jLabel1.setLabelFor(tfConnectionUrl);
        jLabel1.setText(bundle.getString("ConnectionSettingsDialog.lblConnectionUrl.text")); // NOI18N

        jLabel2.setLabelFor(tfUserName);
        jLabel2.setText(bundle.getString("ConnectionSettingsDialog.lblUserName.text")); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setLabelFor(tfSchema);
        jLabel5.setText(bundle.getString("ConnectionSettingsDialog.lblSchema.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(tfUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(tfConnectionUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(tfSchema, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfConnectionUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tfSchema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ConnectionSettingsDialog dialog = new ConnectionSettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfConnectionUrl;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSchema;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the returnStatus
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    public String getUrl() {
        return tfConnectionUrl.getText().trim();
    }

    public String getUserName() {
        return tfUserName.getText();
    }

    public String getSchema() {
        return String.valueOf(tfSchema.getText());
    }

    public String getConnectionName() {
        return tfName.getText();
    }

    public void setUrl(String url) {
        tfConnectionUrl.setText(url);
        checkControls();
    }

    public void setUserName(String userName) {
        tfUserName.setText(userName);
    }

    public void setSchema(String schema) {
        tfSchema.setText(schema);
    }

    public void setConnectionName(String name) {
        tfName.setText(name);
    }

    private void checkControls() {
        tfSchema.setEnabled(isJdbcUrl(getUrl()));
        tfUserName.setEnabled(isJdbcUrl(getUrl()));
    }

    private boolean isJdbcUrl(String url) {
        return url == null || url.isEmpty() || url.toLowerCase().startsWith("jdbc:");
    }

    private class AddConnectionAction extends AbstractAction {

        public void actionPerformed(ActionEvent e) {
            String url = tfConnectionUrl.getText();
            if (url != null) {
                url = url.trim();
            }
            String schema = tfSchema.getText();
            if (schema != null) {
                schema = schema.trim();
            }
            if (url.isEmpty()) {
                JOptionPane.showMessageDialog(ConnectionSettingsDialog.this, bundle.getString("ConnectionSettingsDialog.EmptyUrlMessage"), bundle.getString("ConnectionSettingsDialog.BadSettingsMessage"), JOptionPane.ERROR_MESSAGE);
                tfConnectionUrl.requestFocus();
            } else if (schema.isEmpty() && isJdbcUrl(url)) {
                JOptionPane.showMessageDialog(ConnectionSettingsDialog.this, bundle.getString("ConnectionSettingsDialog.EmptySchemaMessage"), bundle.getString("ConnectionSettingsDialog.BadSettingsMessage"), JOptionPane.ERROR_MESSAGE);
                tfSchema.requestFocus();
            } else {
                doClose(RET_OK);
            }
        }
    }
}
