/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eas.client.model.gui.view;

/**
 *
 * @author mg
 */
public class ScalarCollectionView extends javax.swing.JPanel {

    /**
     * Creates new form ScalarCollectionView
     */
    public ScalarCollectionView() {
        initComponents();
    }

    public String getScalarPropertyName(){
        return txtScalar.getText();
    }
    
    public String getCollectionPropertyName(){
        return txtCollection.getText();
    }
    
    public void setScalarPropertyName(String aValue){
        txtScalar.setText(aValue);
    }
    
    public void setCollectionPropertyName(String aValue){
        txtCollection.setText(aValue);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblScalar = new javax.swing.JLabel();
        lblCollection = new javax.swing.JLabel();
        txtScalar = new javax.swing.JTextField();
        txtCollection = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(lblScalar, org.openide.util.NbBundle.getMessage(ScalarCollectionView.class, "ScalarCollectionView.lblScalar.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblCollection, org.openide.util.NbBundle.getMessage(ScalarCollectionView.class, "ScalarCollectionView.lblCollection.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCollection, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(lblScalar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScalar, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(txtCollection))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScalar)
                    .addComponent(txtScalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCollection)
                    .addComponent(txtCollection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCollection;
    private javax.swing.JLabel lblScalar;
    private javax.swing.JTextField txtCollection;
    private javax.swing.JTextField txtScalar;
    // End of variables declaration//GEN-END:variables
}
