/*
 * UpdProgress.java
 *
 * Created on 26.08.2011, 15:21:16
 */
package com.eas.client.updater;

/**
 *
 * @author AB
 */
public class UpdProgress extends javax.swing.JDialog {

    /** Creates new form UpdProgress */
    public UpdProgress() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCaption = new javax.swing.JLabel();
        jLVersion = new javax.swing.JLabel();
        jpg_Progress = new javax.swing.JProgressBar();
        jLStep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Update Platypus runtime");
        setLocationByPlatform(true);
        setName("fr_Progress"); // NOI18N

        jLCaption.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLCaption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCaption.setName("jl_Caption"); // NOI18N

        jLVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLVersion.setName("jl_Ver"); // NOI18N

        jpg_Progress.setStringPainted(true);

        jLStep.setDoubleBuffered(true);
        jLStep.setFocusable(false);
        jLStep.setInheritsPopupMenu(false);
        jLStep.setName("jl_Step"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLCaption, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jLVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jpg_Progress, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLStep, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLCaption, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpg_Progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLStep, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-419)/2, (screenSize.height-130)/2, 419, 130);
    }// </editor-fold>//GEN-END:initComponents

    /**
     */
    public void run() {
        //new UpdProgress();
        setResizable(false);
        setVisible(true);
        setLocationRelativeTo(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCaption;
    private javax.swing.JLabel jLStep;
    private javax.swing.JLabel jLVersion;
    private javax.swing.JProgressBar jpg_Progress;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jLCaption
     */
    public javax.swing.JLabel getVersion() {
        return jLVersion;
    }

    /**
     * @return the jLVersion
     */
    public javax.swing.JLabel getStep() {
        return jLStep;
    }

    /**
     * @return the jProgressBar1
     */
    public javax.swing.JProgressBar getProgress() {
        return jpg_Progress;
    }

    /**
     * @return the jLCaption
     */
    public javax.swing.JLabel getCaption() {
        return jLCaption;
    }
}
