/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RunFrame.java
 *
 * Created on Jul 13, 2009, 4:16:00 PM
 */
package com.eas.client.forms;

import com.jeta.forms.components.panel.FormPanel;
import java.awt.BorderLayout;

/**
 *
 * @author pk
 */
public class RunFrame extends javax.swing.JFrame {

    private FormPanel formPanel;

    /** Creates new form RunFrame */
    public RunFrame() {
        super();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new RunFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public FormPanel getFormPanel() {
        return formPanel;
    }

    protected void configureContentPane() {
        getContentPane().removeAll();
        getContentPane().add(formPanel, BorderLayout.CENTER);
        if (getExtendedState() != java.awt.Frame.NORMAL) {
            setExtendedState(java.awt.Frame.NORMAL);
        }
    }

    protected void processFormPanel() {
        formPanel.initFromGridView(this);
        //formPanel.getForm().postInitialize(formPanel);
    }

    protected void repaintFrame() {
        repaint();
    }

    public void setFormPanel(FormPanel aFormPanel) {
        formPanel = aFormPanel;
        configureContentPane();
        processFormPanel();
        repaintFrame();
    }
}