/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RunInternalFrame.java
 *
 * Created on Jul 14, 2009, 5:15:56 PM
 */
package com.eas.client.forms;

import com.jeta.forms.components.panel.FormPanel;
import java.awt.BorderLayout;

/**
 *
 * @author pk
 */
public class RunInternalFrame extends javax.swing.JInternalFrame {

    private FormPanel formPanel;

    /** Creates new form RunInternalFrame */
    public RunInternalFrame() {
        initComponents();
    }

    public RunInternalFrame(String title, boolean resizable, boolean closable, boolean maximizable, boolean iconifiable) {
        super(title, resizable, closable, maximizable, iconifiable);
        initComponents();
    }

    public RunInternalFrame(String title, boolean resizable, boolean closable, boolean maximizable) {
        super(title, resizable, closable, maximizable);
        initComponents();
    }

    public RunInternalFrame(String title, boolean resizable, boolean closable) {
        super(title, resizable, closable);
        initComponents();
    }

    public RunInternalFrame(String title, boolean resizable) {
        super(title, resizable);
        initComponents();
    }

    public RunInternalFrame(String title) {
        super(title);
        initComponents();
    }

    @Override
    public void setTitle(String title) {
        super.setTitle(title);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public FormPanel getFormPanel() {
        return formPanel;
    }

    protected void configureContentPane() {
        //getContentPane().removeAll();
        //getContentPane().setLayout(new BorderLayout());
        //getContentPane().add(formPanel, BorderLayout.CENTER);
        //formPanel.setVisible(true);
        //pnlContent.add(formPanel, BorderLayout.CENTER);
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(formPanel, BorderLayout.CENTER);
    }

    protected void processFormPanel() {
        //formPanel.getForm().postInitialize(formPanel);
        formPanel.initFromGridView(this);
    }

    public void setFormPanel(FormPanel aFormPanel) {
        formPanel = aFormPanel;
        configureContentPane();
        processFormPanel();
    }
}
