CREATE TABLE MTD_ENTITIES
   (
    MDENT_ID VARCHAR(200) NOT NULL PRIMARY KEY,
    MDENT_NAME VARCHAR(200),
    MDENT_TYPE DECIMAL(18,0) NOT NULL,
    MDENT_CONTENT_TXT CLOB,
    MDENT_PARENT_ID VARCHAR(200),
    MDENT_ORDER DOUBLE,
    MDENT_CONTENT_TXT_SIZE   DECIMAL(18,0),
    MDENT_CONTENT_TXT_CRC32  DECIMAL(18,0)
    )
#GO
ALTER TABLE MTD_ENTITIES
    ADD CONSTRAINT MTD_ENTITIES_FK61240574157171 FOREIGN KEY(MDENT_PARENT_ID) REFERENCES MTD_ENTITIES(MDENT_ID) ON DELETE CASCADE ON UPDATE CASCADE  
#GO
ALTER TABLE MTD_ENTITIES
    ADD CONSTRAINT MTD_NAMES_UNIQUE UNIQUE(MDENT_PARENT_ID, MDENT_NAME)
#GO
CREATE TABLE MTD_USERS
   (
    USR_NAME VARCHAR(200) NOT NULL PRIMARY KEY,
    USR_PASSWD VARCHAR(200),
    USR_FORM   VARCHAR(200),
    USR_CONTEXT VARCHAR(200),
    USR_ROLES VARCHAR(200),
    USR_PHONE VARCHAR(200),
    USR_EMAIL VARCHAR(200)
   )
#GO
CREATE TABLE MTD_GROUPS
    (
        USR_NAME VARCHAR(200) NOT NULL,
        GROUP_NAME VARCHAR(200)
    )
#GO
ALTER TABLE MTD_GROUPS
    ADD CONSTRAINT MTD_GROUPS_USERS_FK FOREIGN KEY(USR_NAME) REFERENCES MTD_USERS(USR_NAME) ON DELETE CASCADE ON UPDATE CASCADE  
#GO
CREATE TABLE MTD_VERSION
   (
    VERSION_VALUE DECIMAL(18,0) NOT NULL PRIMARY KEY
    )
#GO
INSERT INTO MTD_VERSION (VERSION_VALUE) VALUES (0)
#GO
CREATE TABLE DUMMYTABLE
   (
    DUMMY DECIMAL(18, 0)
   )
#GO
insert into MTD_USERS (USR_NAME, USR_PASSWD)
    VALUES ('admin', 'abe6db4c9f5484fae8d79f2e868a673c')
#GO
insert into MTD_GROUPS (USR_NAME, GROUP_NAME)
    VALUES ('admin', 'admin')
#GO