CREATE TABLE MTD_ENTITIES
   (
    MDENT_ID VARCHAR(200) NOT NULL PRIMARY KEY,
    MDENT_NAME VARCHAR(200),
    MDENT_TYPE DECIMAL(18,0) NOT NULL,
    MDENT_CONTENT_TXT CLOB,
    MDENT_PARENT_ID VARCHAR(200),
    MDENT_ORDER DOUBLE,
    MDENT_CONTENT_TXT_SIZE   DECIMAL(18,0),
    MDENT_CONTENT_TXT_CRC32  DECIMAL(18,0)
    )
#GO
ALTER TABLE MTD_ENTITIES
    ADD CONSTRAINT MTD_ENTITIES_FK61240574157171 FOREIGN KEY(MDENT_PARENT_ID) REFERENCES MTD_ENTITIES(MDENT_ID) ON DELETE CASCADE ON UPDATE CASCADE  
#GO
ALTER TABLE MTD_ENTITIES
    ADD CONSTRAINT MTD_NAMES_UNIQUE UNIQUE(MDENT_PARENT_ID, MDENT_NAME)
#GO
