CREATE TABLE MTD_ENTITIES
(
    MDENT_ID VARCHAR2(200) NOT NULL,
    MDENT_NAME VARCHAR2(200),
    MDENT_TYPE NUMBER NOT NULL,
    MDENT_CONTENT_TXT CLOB,
    MDENT_PARENT_ID VARCHAR2(200),
    MDENT_ORDER FLOAT(126),
    MDENT_CONTENT_TXT_SIZE   NUMBER,
    MDENT_CONTENT_TXT_CRC32  NUMBER,
    CONSTRAINT MTD_ENTITIES_PK PRIMARY KEY(MDENT_ID),
    CONSTRAINT MTD_ENTITIES_FK61240574157171 FOREIGN KEY(MDENT_PARENT_ID) REFERENCES MTD_ENTITIES(MDENT_ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
)
#GO
ALTER TABLE MTD_ENTITIES
    ADD (CONSTRAINT MTD_NAMES_UNIQUE UNIQUE(MDENT_PARENT_ID, MDENT_NAME)
    DEFERRABLE INITIALLY DEFERRED)
#GO
CREATE TABLE DUMMYTABLE
(
    DUMMY NUMBER
)
#GO
