CREATE TABLE MTD_ENTITIES
   (
    MDENT_ID VARCHAR2(200) NOT NULL,
    MDENT_NAME VARCHAR2(200),
    MDENT_TYPE NUMBER NOT NULL,
    MDENT_CONTENT_TXT CLOB,
    MDENT_PARENT_ID VARCHAR2(200),
    MDENT_ORDER FLOAT(126),
    MDENT_CONTENT_TXT_SIZE   NUMBER,
    MDENT_CONTENT_TXT_CRC32  NUMBER,
    CONSTRAINT MTD_ENTITIES_PK PRIMARY KEY(MDENT_ID),
    CONSTRAINT MTD_ENTITIES_FK61240574157171 FOREIGN KEY(MDENT_PARENT_ID) REFERENCES MTD_ENTITIES(MDENT_ID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
    )
#GO
ALTER TABLE MTD_ENTITIES
    ADD (CONSTRAINT MTD_NAMES_UNIQUE UNIQUE(MDENT_PARENT_ID, MDENT_NAME)
    DEFERRABLE INITIALLY DEFERRED)
#GO
CREATE TABLE MTD_USERS
   (
    USR_NAME VARCHAR2(200) NOT NULL,
    USR_PASSWD VARCHAR2(200),
    USR_FORM   VARCHAR2(200),
    USR_CONTEXT VARCHAR2(200),
    USR_ROLES VARCHAR2(200),
    USR_PHONE VARCHAR2(200),
    USR_EMAIL VARCHAR2(200),
    CONSTRAINT MTD_USERS_PK PRIMARY KEY(USR_NAME)
   )
#GO
CREATE TABLE MTD_GROUPS
    (
        USR_NAME VARCHAR2(200) NOT NULL,
        GROUP_NAME VARCHAR2(200)
    )
#GO
ALTER TABLE MTD_GROUPS
    ADD CONSTRAINT MTD_GROUPS_USERS_FK FOREIGN KEY(USR_NAME) REFERENCES MTD_USERS(USR_NAME) ON DELETE CASCADE 
#GO
CREATE TABLE MTD_VERSION
   (
    VERSION_VALUE NUMBER NOT NULL,
    CONSTRAINT MTD_VERSION_PK PRIMARY KEY(VERSION_VALUE)
    )
#GO
INSERT INTO MTD_VERSION (VERSION_VALUE) VALUES (0)
#GO
CREATE TABLE DUMMYTABLE
   (
    DUMMY NUMBER
   )
#GO
insert into MTD_USERS (USR_NAME, USR_PASSWD)
    VALUES ('admin', 'abe6db4c9f5484fae8d79f2e868a673c')
#GO