/* Generated By:JavaCC: Do not edit this line. FormSpecParserTokenManager.java */
package com.jeta.forms.gui.common.parsers;

public class FormSpecParserTokenManager implements FormSpecParserConstants {

    public java.io.PrintStream debugStream = System.out;

    public void setDebugStream(java.io.PrintStream ds) {
        debugStream = ds;
    }

    private final int jjStopStringLiteralDfa_0(int pos, long active0) {
        switch (pos) {
            default:
                return -1;
        }
    }

    private final int jjStartNfa_0(int pos, long active0) {
        return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
    }

    private final int jjStopAtPos(int pos, int kind) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        return pos + 1;
    }

    private final int jjStartNfaWithStates_0(int pos, int kind, int state) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return pos + 1;
        }
        return jjMoveNfa_0(state, pos + 1);
    }

    private final int jjMoveStringLiteralDfa0_0() {
        switch (curChar) {
            case 10:
                return jjStopAtPos(0, 4);
            case 40:
                return jjStopAtPos(0, 46);
            case 41:
                return jjStopAtPos(0, 41);
            case 58:
                return jjStopAtPos(0, 12);
            case 59:
                return jjStopAtPos(0, 11);
            case 66:
            case 98:
                jjmatchedKind = 23;
                return jjMoveStringLiteralDfa1_0(0x1000000L);
            case 67:
            case 99:
                jjmatchedKind = 15;
                return jjMoveStringLiteralDfa1_0(0x100010000L);
            case 68:
            case 100:
                jjmatchedKind = 37;
                return jjMoveStringLiteralDfa1_0(0x4038000000L);
            case 70:
            case 102:
                jjmatchedKind = 19;
                return jjMoveStringLiteralDfa1_0(0x100000L);
            case 71:
            case 103:
                jjmatchedKind = 45;
                return jjMoveStringLiteralDfa1_0(0x100000000000L);
            case 73:
            case 105:
                return jjMoveStringLiteralDfa1_0(0x40000000L);
            case 76:
            case 108:
                jjmatchedKind = 13;
                return jjMoveStringLiteralDfa1_0(0x4000L);
            case 77:
            case 109:
                jjmatchedKind = 33;
                return jjMoveStringLiteralDfa1_0(0x18480000000L);
            case 78:
            case 110:
                jjmatchedKind = 43;
                return jjMoveStringLiteralDfa1_0(0x40000000000L);
            case 80:
            case 112:
                jjmatchedKind = 35;
                return jjMoveStringLiteralDfa1_0(0x1006000000L);
            case 82:
            case 114:
                jjmatchedKind = 17;
                return jjMoveStringLiteralDfa1_0(0x40000L);
            case 84:
            case 116:
                jjmatchedKind = 21;
                return jjMoveStringLiteralDfa1_0(0x400000L);
            default:
                return jjMoveNfa_0(0, 0);
        }
    }

    private int jjMoveStringLiteralDfa1_0(long active0) {
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(0, active0);
            return 1;
        }
        switch (curChar) {
            case 65:
            case 97:
                return jjMoveStringLiteralDfa2_0(active0, 0x10000000000L);
            case 69:
            case 101:
                return jjMoveStringLiteralDfa2_0(active0, 0x4000014000L);
            case 73:
            case 105:
                return jjMoveStringLiteralDfa2_0(active0, 0x8400140000L);
            case 76:
            case 108:
                return jjMoveStringLiteralDfa2_0(active0, 0x38000000L);
            case 77:
            case 109:
                if ((active0 & 0x80000000L) != 0L) {
                    return jjStopAtPos(1, 31);
                } else if ((active0 & 0x100000000L) != 0L) {
                    return jjStopAtPos(1, 32);
                }
                break;
            case 78:
            case 110:
                if ((active0 & 0x40000000L) != 0L) {
                    return jjStopAtPos(1, 30);
                }
                break;
            case 79:
            case 111:
                return jjMoveStringLiteralDfa2_0(active0, 0x40001400000L);
            case 82:
            case 114:
                return jjMoveStringLiteralDfa2_0(active0, 0x101000000000L);
            case 84:
            case 116:
                if ((active0 & 0x4000000L) != 0L) {
                    return jjStopAtPos(1, 26);
                }
                break;
            case 88:
            case 120:
                if ((active0 & 0x2000000L) != 0L) {
                    return jjStopAtPos(1, 25);
                }
                break;
            default:
                break;
        }
        return jjStartNfa_0(0, active0);
    }

    private final int jjMoveStringLiteralDfa2_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(0, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(1, active0);
            return 2;
        }
        switch (curChar) {
            case 69:
            case 101:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
            case 70:
            case 102:
                return jjMoveStringLiteralDfa3_0(active0, 0x4000004000L);
            case 71:
            case 103:
                return jjMoveStringLiteralDfa3_0(active0, 0x40000040000L);
            case 76:
            case 108:
                return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
            case 78:
            case 110:
                if ((active0 & 0x400000000L) != 0L) {
                    jjmatchedKind = 34;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x8000010000L);
            case 79:
            case 111:
                return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L);
            case 80:
            case 112:
                if ((active0 & 0x400000L) != 0L) {
                    return jjStopAtPos(2, 22);
                }
                break;
            case 84:
            case 116:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
            case 85:
            case 117:
                if ((active0 & 0x8000000L) != 0L) {
                    jjmatchedKind = 27;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x30000000L);
            case 88:
            case 120:
                return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L);
            default:
                break;
        }
        return jjStartNfa_0(1, active0);
    }

    private final int jjMoveStringLiteralDfa3_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(1, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(2, active0);
            return 3;
        }
        switch (curChar) {
            case 40:
                if ((active0 & 0x8000000000L) != 0L) {
                    return jjStopAtPos(3, 39);
                } else if ((active0 & 0x10000000000L) != 0L) {
                    return jjStopAtPos(3, 40);
                }
                break;
            case 65:
            case 97:
                return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
            case 70:
            case 102:
                if ((active0 & 0x1000000000L) != 0L) {
                    return jjStopAtPos(3, 36);
                }
                break;
            case 72:
            case 104:
                return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
            case 76:
            case 108:
                if ((active0 & 0x100000L) != 0L) {
                    return jjStopAtPos(3, 20);
                }
                break;
            case 82:
            case 114:
                return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L);
            case 84:
            case 116:
                if ((active0 & 0x4000L) != 0L) {
                    return jjStopAtPos(3, 14);
                }
                return jjMoveStringLiteralDfa4_0(active0, 0x1010000L);
            case 87:
            case 119:
                if ((active0 & 0x100000000000L) != 0L) {
                    return jjStopAtPos(3, 44);
                }
                break;
            case 88:
            case 120:
                if ((active0 & 0x10000000L) != 0L) {
                    return jjStopAtPos(3, 28);
                }
                break;
            case 89:
            case 121:
                if ((active0 & 0x20000000L) != 0L) {
                    return jjStopAtPos(3, 29);
                }
                break;
            default:
                break;
        }
        return jjStartNfa_0(2, active0);
    }

    private final int jjMoveStringLiteralDfa4_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(2, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(3, active0);
            return 4;
        }
        switch (curChar) {
            case 69:
            case 101:
                return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
            case 79:
            case 111:
                return jjMoveStringLiteralDfa5_0(active0, 0x40001000000L);
            case 84:
            case 116:
                if ((active0 & 0x40000L) != 0L) {
                    return jjStopAtPos(4, 18);
                }
                break;
            case 85:
            case 117:
                return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L);
            default:
                break;
        }
        return jjStartNfa_0(3, active0);
    }

    private final int jjMoveStringLiteralDfa5_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(3, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(4, active0);
            return 5;
        }
        switch (curChar) {
            case 76:
            case 108:
                return jjMoveStringLiteralDfa6_0(active0, 0x4000000000L);
            case 77:
            case 109:
                if ((active0 & 0x1000000L) != 0L) {
                    return jjStopAtPos(5, 24);
                }
                break;
            case 82:
            case 114:
                if ((active0 & 0x10000L) != 0L) {
                    return jjStopAtPos(5, 16);
                }
                break;
            case 87:
            case 119:
                if ((active0 & 0x40000000000L) != 0L) {
                    return jjStopAtPos(5, 42);
                }
                break;
            default:
                break;
        }
        return jjStartNfa_0(4, active0);
    }

    private final int jjMoveStringLiteralDfa6_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(4, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(5, active0);
            return 6;
        }
        switch (curChar) {
            case 84:
            case 116:
                if ((active0 & 0x4000000000L) != 0L) {
                    return jjStopAtPos(6, 38);
                }
                break;
            default:
                break;
        }
        return jjStartNfa_0(5, active0);
    }

    private final void jjCheckNAdd(int state) {
        if (jjrounds[state] != jjround) {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }

    private final void jjAddStates(int start, int end) {
        do {
            jjstateSet[jjnewStateCnt++] = jjnextStates[start];
        } while (start++ != end);
    }

    private final void jjCheckNAddTwoStates(int state1, int state2) {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }

    private final void jjCheckNAddStates(int start, int end) {
        do {
            jjCheckNAdd(jjnextStates[start]);
        } while (start++ != end);
    }

    private final void jjCheckNAddStates(int start) {
        jjCheckNAdd(jjnextStates[start]);
        jjCheckNAdd(jjnextStates[start + 1]);
    }
    static final long[] jjbitVec0 = {
        0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
    };

    private final int jjMoveNfa_0(int startState, int curPos) {
        int[] nextStates;
        int startsAt = 0;
        jjnewStateCnt = 27;
        int i = 1;
        jjstateSet[0] = startState;
        int j, kind = 0x7fffffff;
        for (;;) {
            if (++jjround == 0x7fffffff) {
                ReInitRounds();
            }
            if (curChar < 64) {
                long l = 1L << curChar;
                MatchLoop:
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x3ff000000000000L & l) != 0L) {
                                if (kind > 5) {
                                    kind = 5;
                                }
                                jjCheckNAddStates(0, 6);
                            } else if (curChar == 39) {
                                jjCheckNAddStates(7, 9);
                            } else if (curChar == 46) {
                                jjCheckNAdd(1);
                            }
                            break;
                        case 1:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 6) {
                                kind = 6;
                            }
                            jjCheckNAddTwoStates(1, 2);
                            break;
                        case 3:
                            if ((0x280000000000L & l) != 0L) {
                                jjCheckNAdd(4);
                            }
                            break;
                        case 4:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 6) {
                                kind = 6;
                            }
                            jjCheckNAdd(4);
                            break;
                        case 5:
                            if (curChar == 39) {
                                jjCheckNAddStates(7, 9);
                            }
                            break;
                        case 6:
                            if ((0xffffff7fffffffffL & l) != 0L) {
                                jjCheckNAddStates(7, 9);
                            }
                            break;
                        case 7:
                            if (curChar == 39) {
                                jjCheckNAddStates(10, 12);
                            }
                            break;
                        case 8:
                            if (curChar == 39) {
                                jjstateSet[jjnewStateCnt++] = 7;
                            }
                            break;
                        case 9:
                            if ((0xffffff7fffffffffL & l) != 0L) {
                                jjCheckNAddStates(10, 12);
                            }
                            break;
                        case 10:
                            if (curChar == 39 && kind > 8) {
                                kind = 8;
                            }
                            break;
                        case 11:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 5) {
                                kind = 5;
                            }
                            jjCheckNAddStates(0, 6);
                            break;
                        case 12:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 5) {
                                kind = 5;
                            }
                            jjCheckNAdd(12);
                            break;
                        case 13:
                            if ((0x3ff000000000000L & l) != 0L) {
                                jjCheckNAddTwoStates(13, 14);
                            }
                            break;
                        case 14:
                            if (curChar == 46) {
                                jjCheckNAdd(15);
                            }
                            break;
                        case 15:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 6) {
                                kind = 6;
                            }
                            jjCheckNAddTwoStates(15, 16);
                            break;
                        case 17:
                            if ((0x280000000000L & l) != 0L) {
                                jjCheckNAdd(18);
                            }
                            break;
                        case 18:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 6) {
                                kind = 6;
                            }
                            jjCheckNAdd(18);
                            break;
                        case 19:
                            if ((0x3ff000000000000L & l) != 0L) {
                                jjCheckNAddTwoStates(19, 20);
                            }
                            break;
                        case 21:
                            if ((0x280000000000L & l) != 0L) {
                                jjCheckNAdd(22);
                            }
                            break;
                        case 22:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 6) {
                                kind = 6;
                            }
                            jjCheckNAdd(22);
                            break;
                        case 23:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 6) {
                                kind = 6;
                            }
                            jjCheckNAddTwoStates(23, 24);
                            break;
                        case 25:
                            if ((0x280000000000L & l) != 0L) {
                                jjCheckNAdd(26);
                            }
                            break;
                        case 26:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 6) {
                                kind = 6;
                            }
                            jjCheckNAdd(26);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                MatchLoop:
                do {
                    switch (jjstateSet[--i]) {
                        case 2:
                            if ((0x2000000020L & l) != 0L) {
                                jjAddStates(13, 14);
                            }
                            break;
                        case 6:
                            jjCheckNAddStates(7, 9);
                            break;
                        case 9:
                            jjCheckNAddStates(10, 12);
                            break;
                        case 16:
                            if ((0x2000000020L & l) != 0L) {
                                jjAddStates(15, 16);
                            }
                            break;
                        case 20:
                            if ((0x2000000020L & l) != 0L) {
                                jjAddStates(17, 18);
                            }
                            break;
                        case 24:
                            if ((0x2000000020L & l) != 0L) {
                                jjAddStates(19, 20);
                            }
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                MatchLoop:
                do {
                    switch (jjstateSet[--i]) {
                        case 6:
                            if ((jjbitVec0[i2] & l2) != 0L) {
                                jjCheckNAddStates(7, 9);
                            }
                            break;
                        case 9:
                            if ((jjbitVec0[i2] & l2) != 0L) {
                                jjCheckNAddStates(10, 12);
                            }
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 27 - (jjnewStateCnt = startsAt))) {
                return curPos;
            }
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }
    static final int[] jjnextStates = {
        12, 13, 14, 19, 20, 23, 24, 6, 8, 10, 8, 9, 10, 3, 4, 17,
        18, 21, 22, 25, 26,};
    public static final String[] jjstrLiteralImages = {
        "", null, null, null, "\12", null, null, null, null, null, null, "\73", "\72",
        null, null, null, null, null, null, null, null, null, null, null, null, null, null,
        null, null, null, null, null, null, null, null, null, null, null, null, null, null,
        "\51", null, null, null, null, "\50",};
    public static final String[] lexStateNames = {
        "DEFAULT",};
    static final long[] jjtoToken = {
        0x7ffffffff971L,};
    static final long[] jjtoSkip = {
        0xeL,};
    protected SimpleCharStream input_stream;
    private final int[] jjrounds = new int[27];
    private final int[] jjstateSet = new int[54];
    protected char curChar;

    public FormSpecParserTokenManager(SimpleCharStream stream) {
        if (SimpleCharStream.staticFlag) {
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
        }
        input_stream = stream;
    }

    public FormSpecParserTokenManager(SimpleCharStream stream, int lexState) {
        this(stream);
        SwitchTo(lexState);
    }

    public void ReInit(SimpleCharStream stream) {
        jjmatchedPos = jjnewStateCnt = 0;
        curLexState = defaultLexState;
        input_stream = stream;
        ReInitRounds();
    }

    private final void ReInitRounds() {
        int i;
        jjround = 0x80000001;
        for (i = 27; i-- > 0;) {
            jjrounds[i] = 0x80000000;
        }
    }

    public void ReInit(SimpleCharStream stream, int lexState) {
        ReInit(stream);
        SwitchTo(lexState);
    }

    public void SwitchTo(int lexState) {
        if (lexState >= 1 || lexState < 0) {
            throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
        } else {
            curLexState = lexState;
        }
    }

    protected Token jjFillToken() {
        Token t = Token.newToken(jjmatchedKind);
        t.kind = jjmatchedKind;
        String im = jjstrLiteralImages[jjmatchedKind];
        t.image = (im == null) ? input_stream.GetImage() : im;
        t.beginLine = input_stream.getBeginLine();
        t.beginColumn = input_stream.getBeginColumn();
        t.endLine = input_stream.getEndLine();
        t.endColumn = input_stream.getEndColumn();
        return t;
    }
    int curLexState = 0;
    int defaultLexState = 0;
    int jjnewStateCnt;
    int jjround;
    int jjmatchedPos;
    int jjmatchedKind;

    public Token getNextToken() {
        int kind;
        Token specialToken = null;
        Token matchedToken;
        int curPos = 0;

        EOFLoop:
        for (;;) {
            try {
                curChar = input_stream.BeginToken();
            } catch (java.io.IOException e) {
                jjmatchedKind = 0;
                matchedToken = jjFillToken();
                return matchedToken;
            }

            try {
                input_stream.backup(0);
                while (curChar <= 32 && (0x100002200L & (1L << curChar)) != 0L) {
                    curChar = input_stream.BeginToken();
                }
            } catch (java.io.IOException e1) {
                continue EOFLoop;
            }
            jjmatchedKind = 0x7fffffff;
            jjmatchedPos = 0;
            curPos = jjMoveStringLiteralDfa0_0();
            if (jjmatchedKind != 0x7fffffff) {
                if (jjmatchedPos + 1 < curPos) {
                    input_stream.backup(curPos - jjmatchedPos - 1);
                }
                if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
                    matchedToken = jjFillToken();
                    return matchedToken;
                } else {
                    continue EOFLoop;
                }
            }
            int error_line = input_stream.getEndLine();
            int error_column = input_stream.getEndColumn();
            String error_after = null;
            boolean EOFSeen = false;
            try {
                input_stream.readChar();
                input_stream.backup(1);
            } catch (java.io.IOException e1) {
                EOFSeen = true;
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
                if (curChar == '\n' || curChar == '\r') {
                    error_line++;
                    error_column = 0;
                } else {
                    error_column++;
                }
            }
            if (!EOFSeen) {
                input_stream.backup(1);
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
            }
            throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
        }
    }
}
