CREATE TABLE MTD_USERS
(
    USR_NAME VARCHAR(200) NOT NULL,
    USR_PASSWD VARCHAR(200),
    USR_FORM   VARCHAR(200),
    USR_CONTEXT VARCHAR(200),
    USR_ROLES VARCHAR(200),
    USR_PHONE VARCHAR(200),
    USR_EMAIL VARCHAR(200),
    CONSTRAINT PRIMARY KEY(USR_NAME)
)
#GO
CREATE TABLE MTD_GROUPS
(
    USR_NAME VARCHAR(200) NOT NULL,
    GROUP_NAME VARCHAR(200) NOT NULL
)
#GO
ALTER TABLE MTD_GROUPS
    ADD CONSTRAINT MTD_GROUPS_USERS_FK FOREIGN KEY(USR_NAME) REFERENCES MTD_USERS(USR_NAME) ON DELETE CASCADE ON UPDATE CASCADE 
#GO
insert into MTD_USERS (USR_NAME, USR_PASSWD)
    VALUES ('admin', 'abe6db4c9f5484fae8d79f2e868a673c')
#GO
insert into MTD_GROUPS (USR_NAME, GROUP_NAME)
    VALUES ('admin', 'admin')
#GO
