try{
    P.require([
          './model-date'
        , './menu-bar'
        , './flow-pane'
        , './card-pane'
        , './action-event'
        , './text-area'
        , './password-field'
        , './text-field'
        , './key-event'
        , './check-box'
        , './mouse-event'
        , './window-event'
        , './model-check-box'
        , './check-grid-column'
        , './service-grid-column'
        , './item-event'
        , './button'
        , './model-spin'
        , './check-menu-item'
        , './scroll-pane'
        , './model-grid-column'
        , './radio-grid-column'
        , './grid-pane'
        , './label'
        , './value-change-event'
        , './popup-menu'
        , './html-area'
        , './form'
        , './model-formatted-field'
        , './radio-button'
        , './toggle-button'
        , './model-combo'
        , './box-pane'
        , './component-event'
        , './formatted-field'
        , './split-pane'
        , './desktop-pane'
        , './border-pane'
        , './menu-item'
        , './cell-render-event'
        , './menu'
        , './anchors-pane'
        , './tool-bar'
        , './model-text-area'
        , './progress-bar'
        , './container-event'
        , './tabbed-pane'
        , './slider'
        , './button-group'
        , './anchors'
        , './radio-menu-item'
        , './drop-down-button'
        , './model-grid'
        , './menu-separator'
        , './focus-event'
    ]);
}catch(e){
    P.Logger.severe(e);
}
