try{
    P.require([
          './check-menu-item.js'
        , './card-pane.js'
        , './anchors-pane.js'
        , './text-area.js'
        , './button.js'
        , './menu-bar.js'
        , './flow-pane.js'
        , './toggle-button.js'
        , './progress-bar.js'
        , './value-change-event.js'
        , './scroll-pane.js'
        , './model-check-box.js'
        , './tabbed-pane.js'
        , './anchors.js'
        , './model-text-area.js'
        , './menu.js'
        , './border-pane.js'
        , './model-grid-column.js'
        , './window-event.js'
        , './check-box.js'
        , './service-grid-column.js'
        , './check-grid-column.js'
        , './radio-menu-item.js'
        , './button-group.js'
        , './popup-menu.js'
        , './box-pane.js'
        , './model-combo.js'
        , './focus-event.js'
        , './model-spin.js'
        , './tool-bar.js'
        , './container-event.js'
        , './grid-pane.js'
        , './split-pane.js'
        , './mouse-event.js'
        , './menu-item.js'
        , './model-formatted-field.js'
        , './label.js'
        , './form.js'
        , './menu-separator.js'
        , './slider.js'
        , './desktop-pane.js'
        , './action-event.js'
        , './html-area.js'
        , './radio-grid-column.js'
        , './password-field.js'
        , './item-event.js'
        , './cell-render-event.js'
        , './text-field.js'
        , './radio-button.js'
        , './model-date.js'
        , './component-event.js'
        , './model-grid.js'
        , './key-event.js'
        , './formatted-field.js'
        , './drop-down-button.js'
    ]);
}catch(e){
    print(e);
}
